branches:
    - .*
matrix:
    - env: MONKEBASE_CONNECTION=imonke@unix(/run/mysqld/mysqld.sock)/imonke
      image: golang:latest-mysql
    - env: MONKEBASE_CONNECTION=imonke@unix(/run/mysqld/mysqld.sock)/imonke
      image: golang:1.15-mysql
    - env: MONKEBASE_CONNECTION=imonke@unix(/run/mysqld/mysqld.sock)/imonke
      image: golang:1.14-mysql
    - env: MONKEBASE_CONNECTION=imonke@unix(/run/mysqld/mysqld.sock)/imonke
      image: golang:1.13-mysql
before_script:
    - sudo service mysql start
    - sudo mysql -uroot -e"CREATE DATABASE imonke; CREATE USER 'imonke'@'localhost'; GRANT ALL PRIVILEGES ON imonke.* TO 'imonke'@'localhost';"
script:
    - go test ./... -cover -count 1
