language: go
services:
    - mysql
env:
    - MONKEBASE_CONNECTION="travis@tcp(127.0.0.1)/test"
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test' -h 127.0.0.1 -u root
script:
    - go test ./... -count 1 -cover -coverprofile coverage.txt
    - bash <(curl -s https://codecov.io/bash)
