language: go
services:
    - mysql
env:
    - MONKEBASE_CONNECTION="travis@tcp(127.0.0.1)/test"
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test' -h 127.0.0.1 -u root
script:
    - go test ./... -count 1 -cover -coverprofile coverage.txt
    - bash <(curl -s https://codecov.io/bash)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    - docker build . -t gastrodon/imonke-user-create-service:"$TRAVIS_BRANCH"
    - docker push gastrodon/imonke-user-create-service:"$TRAVIS_BRANCH"
    - docker tag gastrodon/imonke-user-create-service:"$TRAVIS_BRANCH" gastrodon/imonke-user-create-service:latest
    - if [ "$TRAVIS_BRANCH" = "master" ]; then docker push gastrodon/imonke-user-create-service:latest; fi
