name: Test

on:
  - push
  - pull_request

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Go version
        run: go version

  build:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Get dependencies
        run: go get ./...
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build package
        run: go build -o job-build-out .

  test:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Get dependencies
        run: go get ./...
      - name: Set up testing database
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: brane
          mysql root password: foobar2000
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests
        env:
          DATABASE_CONNECTION: "root:foobar2000@tcp(localhost)/brane"
          NO_FERROTHORN: "true"
        run: go test ./... -count 1 -cover -coverprofile /tmp/coverage -coverpkg ./...

  coverage:
    runs-on: ubuntu-latest
    needs:
      - setup
      - test
    steps:
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          files: /tmp/coverage
          fail_ci_if_error: true
