name: Test

on:
  - push
  - pull_request

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Go version
        run: go version

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get dependencies
        run: go get ./...
      - name: Build package
        run: go build -o job-build-out .

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Set up testing database
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: brane
          mysql root password: foobar2000
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get dependencies
        run: go get ./...
      - name: Run tests
        env:
          DATABASE_CONNECTION: "root:foobar2000@tcp(localhost)/brane"
          NO_FERROTHORN: "true"
        run: go test ./... -count 1 -cover -coverprofile /tmp/coverage -coverpkg ./...
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          files: /tmp/coverage
          fail_ci_if_error: true

  docker:
    if: ${{ github.ref == 'ref/heads/master' }}
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
      - name: Dockerhub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gastrodon/brane-${{ github.repository }}:latest
